command:
  - ${env}
  - torchrun
  - --standalone
  - --nproc_per_node=2
  - ${program}
  - ${args_no_hyphens}
method: grid
metric:
  goal: minimize
  name: val_l01
parameters:
  model.restart:
    value: glowing-sweep-1
  architecture.nn_params.n_layers:
    value: 32
  architecture.nn_params.time_embed_dim:
    value: 128
  data.N:
    value: 256
  data.data:
    value: CIFAR10
  model.forward_kwargs.bandwidth:
    value: 0.05
  model.forward_kwargs.normalized:
    value: false
  model.forward_kwargs.type:
    value: gaussian
  model.model:
    values:
    - SEDD
  model.seed:
    value: 0
  train.accumulate:
    value: 1
  train.batch_size:
    value: 64
  train.ema:
    value: false
  train.gen_trans_step:
    value: 10
  train.n_epoch:
    value: 10000
program: train.py
