command:
- ${env}
- python3
- ${program}
- ${args_no_hyphens}
method: grid
metric:
  goal: minimize
  name: val_l01
parameters:
  architecture.nn_params.first_mult:
    values:
    - true
    - false
  architecture.nn_params.time_embed_dim:
    value: 512
  data.N:
    values:
    - 4
    - 8
    - 128
  data.data:
    values:
    - CIFAR10
  model.fix_x_t_bias:
    values:
    - true
    - false
  model.forward_kwargs.type:
    value: uniform
  model.logistic_pars:
    values:
    - true
    - false
  model.model:
    values:
    - MaskingDiffusion
    - SEDD
  model.seed:
    values:
    - 0
    - 1
    - 2
program: train.py
