command:
- ${env}
- python3
- ${program}
- ${args_no_hyphens}
method: grid
metric:
  goal: minimize
  name: val_l01
parameters:
  architecture.nn_params.film:
    value: true
  architecture.nn_params.semb_style:
    value: u_inject
  architecture.nn_params.time_embed_dim:
    value: 512
  data.N:
    value: 4
  data.data:
    values:
    - CIFAR10
  model.model:
    values:
    - MaskingDiffusion
    - SEDD
  model.seed:
    values:
    - 0
    - 1
    - 2
program: train.py
