data:
    data: CIFAR10
    N: 128
    conditional: false

model:
    seed: 0
    model: ScheduleCondition
    gamma: 0
    schedule_type: mutual_information
    forward_kwargs:
        type: gaussian
        normalized: true
        bandwidth: 0.14
    hybrid_loss_coeff: 0.0
    logistic_pars: false
    fix_x_t_bias: false
    n_T: 500
    t_max: 0.999
    input_logits: false
    sedd_param: false
    eff_num_classes: 1000000

architecture:
    s_dim: 128
    nn_params:
        s_lengthscale: 50
        time_lengthscale: 1
        n_layers: 8
        time_embed_dim: 0
        not_logistic_pars: false
        semb_style: u_inject
        s_embed_dim: 512
        film: true
        input_logits: false
        first_mult: false
    x0_model_class: KingmaUNet
    width: 32

train:
    batch_size: 16
    n_epoch: 14
    lr: 0.0002
    grad_clip_val: 1
    weight_decay: 0
    gen_trans_step: 2000
