data:
    data: CIFAR10
    N: 128
    conditional: false

model:
    model: ScheduleCondition
    gamma: 0
    schedule_type: linear
    forward_kwargs:
        type: gaussian
        normalized: false
        bandwidth: 0.2
    hybrid_loss_coeff: 0.01
    logistic_pars: true
    fix_x_t_bias: false
    n_T: 500

architecture:
    s_dim: 4
    nn_params:
    x0_model_class: SimpleUNet

train:
    batch_size: 16
    n_epoch: 14
    lr: 0.0002
    grad_clip_val: 1
    weight_decay: 0