program: train.py
method: grid
command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
metric:
  name: val_l01
  goal: minimize
parameters:
  data.data:
    values: [MNIST]
  data.N:
    value: 4
  model.forward_kwargs.type:
      value: uniform
  model.gamma:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  model.fix_x_t_bias:
    values: [true, false]