program: train.py
method: grid
command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
metric:
  name: val_l01
  goal: minimize
parameters:
  data.data:
    values: [CIFAR10]
  data.N:
    value: 128
  model.forward_kwargs.type:
      value: uniform
  model.forward_kwargs.normalized:
      values: [true, false]
  model.forward_kwargs.bandwidth:
      values: [0.1, 0.2, 0.4, 0.8]
  train.train:
    lr: [0.001, 0.0001]