data:
    data: CIFAR10
    N: 128
    conditional: false

model:
    seed: 0
    model: ScheduleCondition
    gamma: 0
    schedule_type: mutual_information
    forward_kwargs:
        type: gaussian
        normalized: true
        bandwidth: 0.14
    hybrid_loss_coeff: 0.0
    logistic_pars: true
    fix_x_t_bias: false
    n_T: 500
    t_max: 0.999

architecture:
    s_dim: 128
    nn_params:
        s_lengthscale: 50
        time_lengthscale: 1
        n_layers: 8
        time_embed_dim: 0
        logistic_pars: true
        semb_style: learn_embed
        s_embed_dim: 512
    x0_model_class: KingmaUNet
    width: 32

train:
    batch_size: 16
    n_epoch: 14
    lr: 0.0002
    grad_clip_val: 1
    weight_decay: 0
    gen_trans_step: 200
