data:
    data: lm1b
    valid: lm1b
    tokenizer_name_or_path: bert-base-uncased 
    cache_dir: /scratch/nvg7279/sched_diff/data_cache
    wrap: true
    N: 30522
    conditional: false

model:
    seed: 0
    model: ScheduleCondition
    gamma: 0
    schedule_type: mutual_information
    forward_kwargs:
        type: bert_embed
        normalize: false
        make_sym: false
        bandwidth: 0.3
        knn: 20
        uniform_rate: 1
    hybrid_loss_coeff: 0.0
    logistic_pars: false
    fix_x_t_bias: false
    n_T: 500
    t_max: 0.999
    input_logits: false

architecture:
    s_dim: 128
    nn_params:
      n_blocks: 8
      hidden_size: 512
      n_heads: 8
      cond_dim: 128
      dropout: 0.1
      scale_by_sigma: true
      tie_word_embeddings: false
      length: 1024
    x0_model_class: DIT

train:
    batch_size: 16
    n_epoch: 14
    lr: 0.0002
    grad_clip_val: 1
    weight_decay: 0
    gen_trans_step: 200
