program: train.py
method: grid
command:
  - python3
  - train.py
  - --config-name=basic_protein
  - ${args_no_hyphens}
metric:
  name: val_l01
  goal: minimize
parameters:
  model.seed:
    value: 0
  model.forward_kwargs.alpha:
    values: [1]
  model.forward_kwargs.beta:
    value: 1.5
  model.gamma:
    values: [0.00001, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  model.forward_kwargs.normalized:
    values: [false]
  model.forward_kwargs.make_sym:
    value: false
  model.model:
    values:
    - ScheduleCondition
  train.pack:
    value: true
  train.batch_size:
    value: 64
  train.n_epoch:
    value: 3
  train.accumulate:
    value: 1
