data:
    data: CIFAR10
    N: 256
    conditional: false

model:
    model: ScheduleCondition
    gamma: 0
    schedule_type: linear
    forward_kwargs:
        type: gaussian
        normalized: true
        bandwidth: 0.14
    hybrid_loss_coeff: 0.01
    logistic_pars: false
    fix_x_t_bias: false
    n_T: 500

architecture:
    s_dim: 4
    nn_params:
    x0_model_class: KingmaUNet

train:
    batch_size: 32
    n_epoch: 200
    lr: 0.0002
    grad_clip_val: 1
    weight_decay: 0
