program: train.py
method: grid
command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
metric:
  name: val_l01
  goal: minimize
parameters:
  model.seed:
    values: [0, 1, 2]
  model.fix_x_t_bias:
    value: false
  data.data:
    values: [CIFAR10]
  data.N:
    value: 4
  model.forward_kwargs.type:
      value: uniform
  model.gamma:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  architecture.nn_params.semb_style:
    value: u_inject
  architecture.nn_params.film:
    value: true