program: train.py
method: grid
command:
  - ${env}
  - python3
  - ${program}
  - --config-name=basic_language
  - ${args_no_hyphens}
metric:
  name: val_l01
  goal: minimize
parameters:
  model.seed:
    value: 0
  model.forward_kwargs.uniform_rate:
    values: [0.1, 0.2, 0.3, 0.99]
  model.forward_kwargs.bandwidth:
    values: [0.05, 1]
  model.forward_kwargs.knn:
    values: [5, 50]
