program: train.py
method: grid
command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
metric:
  name: val_l01
  goal: minimize
parameters:
  model.seed:
    values: [0]
  data.data:
    values: [CIFAR10]
  data.N:
    value: 128
  model.forward_kwargs.type:
      value: gaussian
  model.forward_kwargs.bandwidth:
      values: [0.02, 0.05, 0.1]
  model.forward_kwargs.normalized:
      value: false
  model.gamma:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]