program: train.py
method: grid
command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
metric:
  name: val_l01
  goal: minimize
parameters:
  data.data:
    values: [CIFAR10]
  data.N:
    value: 128
  model.forward_kwargs.type:
      value: uniform
  model.logistic_pars:
    values: [true, false]
  model.hybrid_loss_coeff:
    values: [0.0, 0.01, 0.1]
  train.lr:
    values: [0.001, 0.0001]
  architecture.s_dim:
    values: [2, 4, 8]
    