program: train.py
method: grid
command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
metric:
  name: val_l01
  goal: minimize
parameters:
  model.seed:
    values: [0, 1, 2]
  data.data:
    values: [CIFAR10]
  data.N:
    values: [4, 128]
  model.forward_kwargs.type:
      value: uniform
  architecture.nn_params.input_logits:
    values: [true, false]
  model.input_logits:
    value: architecture.nn_params.input_logits
  architecture.nn_params.first_mult:
    values: [true, false]
    