program: train.py
method: bayes
command:
  - ${env}
  - python3
  - ${program}
  - --config-name=basic_language
  - ${args_no_hyphens}
metric:
  name: val_l01
  goal: minimize
parameters:
  model.seed:
    value: 0
  model.forward_kwargs.uniform_rate:
    distribution: log_uniform
    min: 0.05
    max: 1
  model.forward_kwargs.bandwidth:
    distribution: log_uniform
    min: 0.05
    max: 1
  model.forward_kwargs.knn:
    values: [5, 10, 20, 40, 80]
  model.eff_num_classes:
    values: [300, 1000, 3000, 10000]

